### ISSUE TITLE
Windows 10 Clock character missing. 

### ISSUE THREAD

**Issue by Vivimagic** [blaisck/sfwin#2]
![2018-04-24 14_30_16-](https://user-images.githubusercontent.com/20373216/39190279-2cf87710-47cc-11e8-83ba-0232a5354d25.png)
Attach is a screenshot with the issue. Seems like the font does not support ":" in the Windows 10 Clock

**Comment by aishalih** [comment]
@Vivimagic : 
I updated to the latest version. Try to download and re-install the fonts.

**Comment by DestroyTargetNo** [comment]
Downloading and reinstalling the font seguisym.ttf (ie. Segoe UI Symbol) seems to solve this issue.

**Comment by Angygz07** [comment]
How to Install it or Which font To install

**Comment by aishalih** [comment]
@Angygz07 : 
If you are using Windows, just download the TTF version. 
Just right click at the font files, and then Install Font
