### ISSUE TITLE
Add SF Mono Fonts

### ISSUE THREAD

**Issue by Shoggomo** [blaisck/sfwin#3]
There are other repos with them, but for the sake of completeness it'd be nice to have them here too.

**Comment by aishalih** [comment]
Can you show me what you mean, because I just convert the fonts from the official website 
https://developer.apple.com/fonts/ and there's no update.

**Comment by Shoggomo** [comment]
Acording to [this article](https://medium.com/@shashikant.jagtap/getting-apples-sf-mono-font-in-macos-1de5183add84) it comes with the Terminal app and Xcode.

**Comment by aishalih** [comment]
Thanks for the information, I just add SFMono.
