### ISSUE TITLE
Microsoft Word displaying SF Mono in italics

### ISSUE THREAD

**Issue by dotnetdan** [blaisck/sfwin#7]
Microsoft Word refuses to display SF Mono in the 'regular' style:

![image](https://user-images.githubusercontent.com/500965/52870892-e276f880-3116-11e9-88c7-75fe4787e3c1.png)

In comparison, Wordpad is works fine:

![image](https://user-images.githubusercontent.com/500965/52870779-a04db700-3116-11e9-9581-5da3e9364b7e.png)

Any idea why this is happening? I tried restarting the Windows font caching services, and rebooted my machine, but no luck.

**Comment by dotnetdan** [comment]
Somehow I had both the TTF and OTF installed simultaneously. I manually deleted all the fonts from cmd and then reinstalled just the OTF to fix this.

**Comment by Merbikoss** [comment]
it happened on me too. idk why this happens but ill try to fix it.
