### ISSUE TITLE
Not all stylings install on Windows 10

### ISSUE THREAD

**Issue by jkabealo** [blaisck/sfwin#8]
When looking at the SF Pro Text font family there are a ton of different stylings i.e. black, blackitalic, bold, bolditalic. When I go to install bold when bold italic is already installed Windows says that bold is already installed but when I go to use the font in after effects or illustrator bolditalic is the only option. Which gets to my issue that only some stylings actually get installed and are usable in adobe products. Of course is something like openoffice or word there is a toggle to make the text italic or bold but adobe lists all stylings it can detect.
Any workaround for getting all the different stylings working on windows 10?

**Comment by aishalih** [comment]
Have you tried both formats (`.ttf` and `.otf`)?

**Comment by yell0wsuit** [comment]
You need to change the font metadata, Windows does not support weights other than Bold/Regular/(Bold) Italic

**Comment by mkzhx** [comment]
Adding onto windyboy1704, use something like Fontlab to edit font metadata: change everything that's not "Regular" (ex: ultralight, light, thin, medium, heavy, black, etc.) to have their own style group (don't change the family, just the style group). Ex 1: Change the style group of "SF Pro Display Thin" from just "SF Pro Display" to "SF Pro Display Thin", and set the styling to "regular". Ex 2: Change the style group of "SF Pro Display Thin Italic" from "SF Pro Display" to "SF Pro Display Thin" as well, except this time, change the styling the "italic". This will make different style groups appear as different fonts in Windows programs. An image is attached.
![Github_04102019](https://user-images.githubusercontent.com/56149628/66188662-3432ba00-e6cb-11e9-962a-da26afcc5118.png)

**Comment by NightFurySL2001** [comment]
@jkabealo I had edited the font to match the font family for Windows program with minimal (at least the best `ttx` and my programming skillls can do) destruction to the font. Please try this and check if this is working.

[SFWin for Office.](https://github.com/NightFurySL2001/sfwin-office)

**Comment by yell0wsuit** [comment]
@NightFurySL2001 
Since the fonts here have problem with tittle (small dot on `i` and `j`) due to the way the author converted them -- and they are outdated, I suggest you should extract `ttx` from official Apple fonts, then edit the metadata from there.
TTF versions here are also not true to the Apple one as seen in https://support.apple.com/, if you know about CSS you should probably get TTFs from there too.

**Comment by NightFurySL2001** [comment]
@purifiedh2o I see that you did have a San Francisco repo on your account, may I ask if it is updated to newest? I could try download the official Apple fonts, but when I tried editing the New York font from their source, the italics didnt appear to be linked to their counterparts. Could you possibly check it out? Thanks.

**Comment by yell0wsuit** [comment]
Yes, they all updated. Apple sometimes updates their fonts so I usually check it twice a month (the latest for SF Pro was in September or so iirc).

For New York font, did you try picking one optical size as a basis? Windows easily confuses `Medium` in the name with Medium weight.

**Comment by NightFurySL2001** [comment]
@purifiedh2o I'll check your fonts and edit them in a new repo. 

I just drop everything into ttx and batch edit the font. The font weights are showing up correctly but the italics are not linked. You can reach me at nightfurysl2001@Outlook.my so we can continue on email. Attached are fonts that I had generated.
[New-York-Win.zip](https://github.com/blaisck/sfwin/files/4198823/New-York-Win.zip)
